version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - PORT=7860
    volumes:
      # Optional: Mount for development (uncomment if needed)
      # - ./api:/app
      # - /app/__pycache__
      # - /app/.ruff_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - img-edit-network

networks:
  img-edit-network:
    driver: bridge
