# Docker Compose configuration for development

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - PORT=7860
      - PYTHONPATH=/app
    volumes:
      # Mount source code for live reloading
      - .:/app
      # Exclude cache directories
      - /app/__pycache__
      - /app/.ruff_cache
      - /app/.pytest_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - img-edit-network

networks:
  img-edit-network:
    driver: bridge
