name: Deploy API to Hugging Face Spaces

on:
  push:
    branches: [main]
    # paths:
    #   - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install --system --no-cache-dir .

      # - name: Run tests
      #   run: |
      #     python -m pytest tests/ -v

      - name: Install HF CLI
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade huggingface_hub

      - name: Deploy to Hugging Face Spaces
        if: github.ref == 'refs/heads/main'
        run: |
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy to HF Spaces: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || true

      - name: Push to existing Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_URL: ${{ secrets.HF_SPACE_URL }}
        run: |
          # Push to Hugging Face Spaces (Docker SDK + Git)
          git branch -M main
          huggingface-cli login --token "$HF_TOKEN"
          git remote add origin $HF_SPACE_URL
          git push -f origin main
